version: "3.8"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 67:67/udp
            - 80:80/tcp
            - 443:443/tcp
        dns:
            - 127.0.0.1
            - 1.1.1.1
        network_mode: "host"
        environment:
            TZ: 'Germany/Berlin'
            WEBPASSWORD: <your password>
            IPv6: 'true'
            #FTLCONF_REPLY_ADDR4: <your host IP>
            #FTLCONF_REPLY_ADDR6: <your host IPv6>
            #ServerIPv6: <your host IPv6>
            DNSSEC: "true"
            DNS_BOGUS_PRIV: "false"
            #sample DNS configuration
            PIHOLE_DNS_: 9.9.9.11;149.112.112.11;2620:fe::11;2620:fe::fe:11;9.9.9.9;149.112.112.112;2620:fe::fe;2620:fe::9;1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001;208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53
            # Volumes store your data between container upgrades
        volumes:
            - './etc-pihole/:/etc/pihole/'
            - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
            # Recommended but not required (DHCP needs NET_ADMIN)
            # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
